# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_top) {transformation: [-1.4583f,0f,0f,0.0313f,0f,1.4583f,0f,0.1562f,0f,0f,-1.4583f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,0.2812f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":0,"posy":0.3437499999999999,"posz":0,"roty":0,"rotx":0}}}