# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute on passengers if entity @s[tag=aj.blueprint.data] unless data entity @s {data:{rigHash: 'a93ee07dc67c102eb7a965d77096aff5f333f56513e88f74ffd44b6a33b51f26'}} on vehicle run function animated_java:blueprint/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1