# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.planta.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'planta', 'function_path': 'animated_java:planta/animations/animation.model.bite/play'}
tag @s add aj.planta.animation.animation.model.bite.playing
scoreboard players set @s aj.animation.model.bite.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:planta/animations/animation.model.bite/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only