# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.planta.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'planta', 'function_path': 'animated_java:planta/variants/warm/apply'}
execute on passengers if entity @s[tag=aj.planta.bone.top] run function animated_java:planta/variants/warm/zzz/apply_to_bone_top
return 1