# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.planta.node.top] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.planta.node.bottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bottom set from storage aj:uuid main.out