# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.planta.root] run return 0
execute on passengers if entity @s[tag=aj.planta.data] unless data entity @s {data:{rigHash: 'f85fe097340ed01be920bb263be15e640c6f73a9810ca950603320cf3ff819f7'}} on vehicle run function animated_java:planta/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1